export const mainQuizzes = {
    '1': {
        name: 'Jeopardy Quiz',
        question1:'It can mean to drain of energy or the gases that escape from an engine.',
        answer1:'Exhaust',
        question2:'Job of the person hired to renovate your house, perhaps after you find an architect.',
        answer2:'Contractor',
        question3:'It’s a small thin round of ground beef or peppermint candy.',
        answer3:'Answer: A patty.',
        question4:'The main story line of a literary work, or the spot where you could be buried.',
        answer4:'A plot.',
        question5:'In Oct. 1995 her “Jagged Little Pill” became the first album by a Canadian female to reach No. 1 in the U.S..',
        answer5:'Alanis Morissette',
        id: '1',
    },
    '2': {
        name: 'Celebrity Quiz',
        question1:'It can mean to drain of energy or the gases that escape from an engine.',
        answer1:'Exhaust',
        question2:'Job of the person hired to renovate your house, perhaps after you find an architect.',
        answer2:'Contractor',
        question3:'It’s a small thin round of ground beef or peppermint candy.',
        answer3:'Answer: A patty.',
        question4:'The main story line of a literary work, or the spot where you could be buried.',
        answer4:'A plot.',
        question5:'In Oct. 1995 her “Jagged Little Pill” became the first album by a Canadian female to reach No. 1 in the U.S..',
        answer5:'Alanis Morissette',
        id: '2',
    }
}